spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    url : jdbc:mysql://localhost:3306/ims?createDatabaseIfNotExist=true
    username: root
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
